### ISSUE TITLE
User Edit Bug.

### ISSUE THREAD

**Issue by dhsagar** [milon521/laravel-todo#1]
There is a bug in your user profile edit system. If a user is logged in and get to his profile to edit the url is  /user/{id}/edit. And he can edit his profile. The funny thing is if a user is logged in and change the id to a valid user then he can also edit that user's profile. 
IE: 
if i am a user with id 10. if i go to /user/10/edit then i can edit my profile with credential values. If i change the url id to 7. then i can access the 7th user profile and also can edit that.

Tried to create a pull request, as i havn't grant permission failed. You can look into this. Or create a branch where i can push my changes to that solves this problem.

**Comment by ehzawad** [comment]
cp .env.exapmle .env      you have done a silly mistake  ...
cp .env.example .env    the correction...

**Comment by milon** [comment]
thanks, @ehzShelter Fixed.

**Comment by ehzawad** [comment]
Welcome :)
